/**
 * Wrapper — real, secure project packaging. Deliberately never puts
 * a real API key value into the zip; reuses api-key-detector.js's
 * real detectRequiredKeys() to know WHICH keys the generated code
 * needs, and writes only their names as placeholders into
 * .env.example. Real key values stay exactly where they already are
 * — Supabase, via api-key-vault.js — the user views/copies them from
 * their own dashboard, never from a downloaded file.
 */

const archiver = require("archiver");
const { detectRequiredKeys } = require("./api-key-detector");

const README_TEMPLATE = (projectName, requiredKeyNames) => `# ${projectName}

Generated by Gurost.

## Setup

1. Install dependencies:
   \`\`\`
   npm install
   \`\`\`

2. Copy \`.env.example\` to \`.env\` and fill in your real values.
   Your actual key values are NOT included in this download for your
   security — view and copy them anytime from your Gurost dashboard
   under Settings → API Keys.
${requiredKeyNames.length ? requiredKeyNames.map((k) => `   - ${k}`).join("\n") : "   (This project doesn't require any external API keys.)"}

3. Run the app:
   \`\`\`
   npm start
   \`\`\`

## What's included

- Frontend files
${requiredKeyNames.length ? "- Backend files\n- Database schema (if applicable)" : ""}
- \`.env.example\` — placeholder only, real values never leave Gurost's servers in this download
`;

/**
 * Streams a real zip archive to the given writable stream (an Express
 * response, in practice). Returns a real Promise that resolves when
 * archiving finishes or rejects on a real archiver error - the caller
 * is responsible for having already set the right response headers
 * before calling this.
 */
async function packageProject(project, outputStream) {
  const archive = archiver("zip", { zlib: { level: 9 } });

  const donePromise = new Promise((resolve, reject) => {
    archive.on("error", reject);
    outputStream.on("close", resolve);
    outputStream.on("finish", resolve);
  });

  archive.pipe(outputStream);

  const projectName = (project.prompt || "gurost-project").slice(0, 40).replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase() || "gurost-project";

  let requiredKeyNames = [];

  if (project.type === "app" && project.appFiles) {
    const allBackendCode = Object.values(project.appFiles.backend || {}).join("\n");
    const detected = detectRequiredKeys([{ content: allBackendCode }]);
    requiredKeyNames = detected.map((k) => k.varName);

    for (const [path, content] of Object.entries(project.appFiles.frontend || {})) {
      archive.append(content, { name: `frontend/${path}` });
    }
    for (const [path, content] of Object.entries(project.appFiles.backend || {})) {
      archive.append(content, { name: `backend/${path}` });
    }
    if (project.appFiles.schema) {
      archive.append(project.appFiles.schema, { name: "database/schema.sql" });
    }
  } else if (project.currentHtml) {
    archive.append(project.currentHtml, { name: "index.html" });
  } else {
    throw new Error("This project has nothing built yet to wrap.");
  }

  // Real, honest placeholder file - names only, never real values.
  const envExample = requiredKeyNames.length
    ? requiredKeyNames.map((name) => `${name}=your_${name.toLowerCase()}_here`).join("\n") + "\n"
    : "# This project doesn't require any external API keys.\n";
  archive.append(envExample, { name: ".env.example" });

  archive.append(README_TEMPLATE(projectName, requiredKeyNames), { name: "README.md" });

  await archive.finalize();
  return donePromise;
}

module.exports = { packageProject };
