/**
 * Creates a GitHub repo and commits a set of generated files to it in one
 * atomic commit (blobs -> tree -> commit -> ref update), rather than N
 * sequential PUT-file calls. This exists because Render (and Railway)
 * deploy backends from a Git repository — there's no "POST raw files,
 * get a live backend" endpoint the way Vercel has for static sites.
 *
 * Requires GITHUB_TOKEN with repo-creation scope (a classic PAT with
 * `repo` scope, or a fine-grained token with Contents + Administration
 * read/write on your account).
 */

const GITHUB_API = "https://api.github.com";

function headers() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not configured on server.");
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json"
  };
}

async function ghFetch(path, options = {}) {
  const response = await fetch(`${GITHUB_API}${path}`, { ...options, headers: headers() });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(`GitHub API error (${response.status}) on ${path}: ${JSON.stringify(data).slice(0, 300)}`);
  }
  return data;
}

async function getAuthenticatedUser() {
  const data = await ghFetch("/user");
  return data.login;
}

async function createRepo(name) {
  return ghFetch("/user/repos", {
    method: "POST",
    body: JSON.stringify({
      name,
      private: false, // must be public for Render's "public Git repository URL" deploy path, which needs no Render-side GitHub app install
      auto_init: true, // creates an initial commit so we have a base ref/tree to build on
      description: "Auto-generated by Gurost"
    })
  });
}

// files: [{ path, content }]. Commits all of them in a single commit on main.
async function commitFiles(owner, repo, files) {
  const ref = await ghFetch(`/repos/${owner}/${repo}/git/refs/heads/main`);
  const baseCommitSha = ref.object.sha;
  const baseCommit = await ghFetch(`/repos/${owner}/${repo}/git/commits/${baseCommitSha}`);
  const baseTreeSha = baseCommit.tree.sha;

  const blobs = await Promise.all(
    files.map(async (f) => {
      const blob = await ghFetch(`/repos/${owner}/${repo}/git/blobs`, {
        method: "POST",
        body: JSON.stringify({ content: f.content, encoding: "utf-8" })
      });
      return { path: f.path, mode: "100644", type: "blob", sha: blob.sha };
    })
  );

  const tree = await ghFetch(`/repos/${owner}/${repo}/git/trees`, {
    method: "POST",
    body: JSON.stringify({ base_tree: baseTreeSha, tree: blobs })
  });

  const commit = await ghFetch(`/repos/${owner}/${repo}/git/commits`, {
    method: "POST",
    body: JSON.stringify({
      message: "Initial generated code (Gurost)",
      tree: tree.sha,
      parents: [baseCommitSha]
    })
  });

  await ghFetch(`/repos/${owner}/${repo}/git/refs/heads/main`, {
    method: "PATCH",
    body: JSON.stringify({ sha: commit.sha })
  });

  return commit.sha;
}

/**
 * Creates a fresh public repo named gurost-<projectId prefix> and pushes
 * the given files to it in one commit. Returns the repo's HTTPS URL for
 * handing to Render.
 */
async function pushGeneratedRepo(files, projectId) {
  const owner = await getAuthenticatedUser();
  const repoName = `gurost-${projectId.slice(0, 8)}`;
  await createRepo(repoName);
  await commitFiles(owner, repoName, files);
  return { repoUrl: `https://github.com/${owner}/${repoName}`, owner, repo: repoName };
}

module.exports = { pushGeneratedRepo, getAuthenticatedUser, createRepo, commitFiles };
